//
// RB_FLASH.h (STM32F2xx)
//

/// \file RB_FLASH.h
/// Registerbankdeclaration zur Programmierung des Flash-Speichers.

#ifndef guard_RB_FLASH_H
# define  guard_RB_FLASH_H

# include <RB.h>

/// Datentyp für FLASH-Registerbank, s. PM0059 Programming Manual, Abschnitt 1.8.
typedef struct __regbank_FLASH
{
  WORD ACR;                     ///< Access control register.
  WORD KEYR;                    ///< Key register.
  WORD OPTKEYR;                 ///< Options key register.
  WORD SR;                      ///< Status register.
  WORD CR;                      ///< Control register.
  WORD OPTCR;                   ///< Option control register.
} RegbankTypeFLASH;

/// FLASH-Registerbank.
extern RegbankTypeFLASH volatile rbFLASH;

/// \cond RB_DEFS

// ACR

# define MASK_FLASH_ACR_LATENCY 0xFU
# define MASK_FLASH_ACR_LATENCY_0WS 0U
# define MASK_FLASH_ACR_LATENCY_3WS 3U
# define MASK_FLASH_ACR_LATENCY_5WS 5U
# define MASK_FLASH_ACR_LATENCY_7WS 7U

# define INDX_FLASH_ACR_PRFTEN  8
# define MASK_FLASH_ACR_PRFTEN  REG_BITMASK(FLASH_ACR_PRFTEN)

# define INDX_FLASH_ACR_ICEN    9
# define MASK_FLASH_ACR_ICEN    REG_BITMASK(FLASH_ACR_ICEN)

# define INDX_FLASH_ACR_DCEN    10
# define MASK_FLASH_ACR_DCEN    REG_BITMASK(FLASH_ACR_DCEN)

// KEYR

# define MASK_FLASH_KEYR_KEY1   0x45670123U
# define MASK_FLASH_KEYR_KEY2   0xCDEF89ABU

// SR

# define INDX_FLASH_SR_EOP      0
# define MASK_FLASH_SR_EOP      REG_BITMASK(FLASH_SR_EOP)

# define INDX_FLASH_SR_OPERR    1
# define MASK_FLASH_SR_OPERR    REG_BITMASK(FLASH_SR_OPERR)

# define INDX_FLASH_SR_WRPERR   4
# define MASK_FLASH_SR_WRPERR   REG_BITMASK(FLASH_SR_WRPERR)

# define INDX_FLASH_SR_PGAERR   5
# define MASK_FLASH_SR_PGAERR   REG_BITMASK(FLASH_SR_PGAERR)

# define INDX_FLASH_SR_PGPERR   6
# define MASK_FLASH_SR_PGPERR   REG_BITMASK(FLASH_SR_PGPERR)

# define INDX_FLASH_SR_PGSERR   7
# define MASK_FLASH_SR_PGSERR   REG_BITMASK(FLASH_SR_PGSERR)

# define INDX_FLASH_SR_BSY      16
# define MASK_FLASH_SR_BSY      REG_BITMASK(FLASH_SR_BSY)

// CR

# define INDX_FLASH_CR_PG       0
# define MASK_FLASH_CR_PG       REG_BITMASK(FLASH_CR_PG)

# define INDX_FLASH_CR_SER      1
# define MASK_FLASH_CR_SER      REG_BITMASK(FLASH_CR_SER)

# define INDX_FLASH_CR_MER      2
# define MASK_FLASH_CR_MER      REG_BITMASK(FLASH_CR_MER)

# define INDX_FLASH_CR_SNB      3
# define MASK_FLASH_CR_SNB      (0xFU << INDX_FLASH_CR_SNB)

# define INDX_FLASH_CR_PSIZE    8
# define MASK_FLASH_CR_PSIZE    (3U << INDX_FLASH_CR_PSIZE)    
# define MASK_FLASH_CR_PSIZE_BYTE (0U << INDX_FLASH_CR_PSIZE)    
# define MASK_FLASH_CR_PSIZE_HWRD (1U << INDX_FLASH_CR_PSIZE)    
# define MASK_FLASH_CR_PSIZE_WORD (2U << INDX_FLASH_CR_PSIZE)    

# define INDX_FLASH_CR_EOPIE    24
# define MASK_FLASH_CR_EOPIE    REG_BITMASK(FLASH_CR_EOPIE)

# define INDX_FLASH_CR_ERRIE    25
# define MASK_FLASH_CR_ERRIE    REG_BITMASK(FLASH_CR_ERRIE)

# define INDX_FLASH_CR_STRT     16
# define MASK_FLASH_CR_STRT     REG_BITMASK(FLASH_CR_STRT)

# define INDX_FLASH_CR_LOCK     31
# define MASK_FLASH_CR_LOCK     REG_BITMASK(FLASH_CR_LOCK)


/// Größe der ersten 4 Flash-Speicherbänken (in Bytes).
# define FLASH_SMALLSEC_SIZE    (16U * 1024U)

# define FLASH_SECTOR00_ADDR    IROM_START
# define FLASH_SECTOR00_SIZE    FLASH_SMALLSEC_SIZE
# define FLASH_SECTOR01_ADDR    (FLASH_SECTOR00_ADDR + FLASH_SECTOR00_SIZE)   
# define FLASH_SECTOR01_SIZE    FLASH_SMALLSEC_SIZE
# define FLASH_SECTOR02_ADDR    (FLASH_SECTOR01_ADDR + FLASH_SECTOR01_SIZE)   
# define FLASH_SECTOR02_SIZE    FLASH_SMALLSEC_SIZE
# define FLASH_SECTOR03_ADDR    (FLASH_SECTOR02_ADDR + FLASH_SECTOR02_SIZE)   
# define FLASH_SECTOR03_SIZE    FLASH_SMALLSEC_SIZE
# define FLASH_SECTOR04_ADDR    (FLASH_SECTOR03_ADDR + FLASH_SECTOR03_SIZE)   
# define FLASH_SECTOR04_SIZE    (64U * 1024U)
# define FLASH_SECTOR05_ADDR    (FLASH_SECTOR04_ADDR + FLASH_SECTOR04_SIZE)   
# define FLASH_SECTOR05_SIZE    (128U * 1024U)
# define FLASH_SECTOR06_ADDR    (FLASH_SECTOR05_ADDR + FLASH_SECTOR05_SIZE)   
# define FLASH_SECTOR06_SIZE    (128U * 1024U)
# define FLASH_SECTOR07_ADDR    (FLASH_SECTOR06_ADDR + FLASH_SECTOR06_SIZE)   
# define FLASH_SECTOR07_SIZE    (128U * 1024U)
# define FLASH_SECTOR08_ADDR    (FLASH_SECTOR07_ADDR + FLASH_SECTOR07_SIZE)   
# define FLASH_SECTOR08_SIZE    (128U * 1024U)
# define FLASH_SECTOR09_ADDR    (FLASH_SECTOR08_ADDR + FLASH_SECTOR08_SIZE)   
# define FLASH_SECTOR09_SIZE    (128U * 1024U)
# define FLASH_SECTOR10_ADDR    (FLASH_SECTOR09_ADDR + FLASH_SECTOR09_SIZE)   
# define FLASH_SECTOR10_SIZE    (128U * 1024U)
# define FLASH_SECTOR11_ADDR    (FLASH_SECTOR10_ADDR + FLASH_SECTOR11_SIZE)   
# define FLASH_SECTOR11_SIZE    (128U * 1024U)

/// \endcond

#endif
