//
// RB_RCC_AHB.h (STM32F2xx)
//

/// \file RB_RCC_AHB.h
/// AHB definitions for  reset and clock control (RCC).

#ifndef guard_RB_RCC_AHB_H
# define  guard_RB_RCC_AHB_H

# define INDX_RCC_AHB1_ETHPTP   28
# define MASK_RCC_AHB1_ETHPTP   (WORD)REG_BITMASK(RCC_AHB1_ETHPTP)

# define INDX_RCC_AHB1_ETHRX    27
# define MASK_RCC_AHB1_ETHRX    (WORD)REG_BITMASK(RCC_AHB1_ETHRX)

# define INDX_RCC_AHB1_ETHTX    26
# define MASK_RCC_AHB1_ETHTX    (WORD)REG_BITMASK(RCC_AHB1_ETHTX)

# define INDX_RCC_AHB1_ETHMAC   25
# define MASK_RCC_AHB1_ETHMAC   (WORD)REG_BITMASK(RCC_AHB1_ETHMAC)

# define INDX_RCC_AHB1_DMA_2D   23
# define MASK_RCC_AHB1_DMA_2D   (WORD)REG_BITMASK(RCC_AHB1_DMA_2D)

# define INDX_RCC_AHB1_DMA2     22
# define MASK_RCC_AHB1_DMA2     (WORD)REG_BITMASK(RCC_AHB1_DMA2)

# define INDX_RCC_AHB1_DMA1     21
# define MASK_RCC_AHB1_DMA1     (WORD)REG_BITMASK(RCC_AHB1_DMA1)

# define INDX_RCC_AHB1_CCM      20                    // STM32F4xx only (core coupled memory)
# define MASK_RCC_AHB1_CCM      (WORD)REG_BITMASK(RCC_AHB1_CCM)

# define INDX_RCC_AHB1_TCM      20                    // STM32F7xx only (tightly coupled memory)
# define MASK_RCC_AHB1_TCM      (WORD)REG_BITMASK(RCC_AHB1_TCM)

# define INDX_RCC_AHB1_BKPSRAM  18
# define MASK_RCC_AHB1_BKPSRAM  (WORD)REG_BITMASK(RCC_AHB1_BKPSRAM)

# define INDX_RCC_AHB1_CRC      12
# define MASK_RCC_AHB1_CRC      (WORD)REG_BITMASK(RCC_AHB1_CRC)

# define INDX_RCC_AHB1_GPIOK    10
# define MASK_RCC_AHB1_GPIOK    (WORD)REG_BITMASK(RCC_AHB1_GPIOK)

# define INDX_RCC_AHB1_GPIOJ    9
# define MASK_RCC_AHB1_GPIOJ    (WORD)REG_BITMASK(RCC_AHB1_GPIOJ)

# define INDX_RCC_AHB1_GPIOI    8
# define MASK_RCC_AHB1_GPIOI    (WORD)REG_BITMASK(RCC_AHB1_GPIOI)

# define INDX_RCC_AHB1_GPIOH    7
# define MASK_RCC_AHB1_GPIOH    (WORD)REG_BITMASK(RCC_AHB1_GPIOH)

# define INDX_RCC_AHB1_GPIOG    6
# define MASK_RCC_AHB1_GPIOG    (WORD)REG_BITMASK(RCC_AHB1_GPIOG)

# define INDX_RCC_AHB1_GPIOF    5
# define MASK_RCC_AHB1_GPIOF    (WORD)REG_BITMASK(RCC_AHB1_GPIOF)

# define INDX_RCC_AHB1_GPIOE    4
# define MASK_RCC_AHB1_GPIOE    (WORD)REG_BITMASK(RCC_AHB1_GPIOE)

# define INDX_RCC_AHB1_GPIOD    3
# define MASK_RCC_AHB1_GPIOD    (WORD)REG_BITMASK(RCC_AHB1_GPIOD)

# define INDX_RCC_AHB1_GPIOC    2
# define MASK_RCC_AHB1_GPIOC    (WORD)REG_BITMASK(RCC_AHB1_GPIOC)

# define INDX_RCC_AHB1_GPIOB    1
# define MASK_RCC_AHB1_GPIOB    (WORD)REG_BITMASK(RCC_AHB1_GPIOB)

# define INDX_RCC_AHB1_GPIOA    0
# define MASK_RCC_AHB1_GPIOA    (WORD)REG_BITMASK(RCC_AHB1_GPIOA)

# define INDX_RCC_AHB2_RNG      6
# define MASK_RCC_AHB2_RNG      (WORD)REG_BITMASK(RCC_AHB2_RNG)

# define INDX_RCC_AHB2_DCMI     0
# define MASK_RCC_AHB2_DCMI     (WORD)REG_BITMASK(RCC_AHB2_DCMI)

# define INDX_RCC_AHB3_FMC      0
# define MASK_RCC_AHB3_FCM      (WORD)REG_BITMASK(RCC_AHB3_FMC)

#endif
